alter table public.companies
  add column if not exists neighborhood text;

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    name text not null,
    category text,
    description text,
    base_price bigint,
    active boolean not null default true,
    display_order integer not null default 0,
    color text
);

create table if not exists public.lead_sources (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    name text not null,
    active boolean not null default true,
    display_order integer not null default 0
);

alter table public.deals
  add column if not exists product_id bigint,
  add column if not exists lead_source_id bigint,
  add column if not exists primary_contact_id bigint,
  add column if not exists next_follow_up_at timestamp with time zone,
  add column if not exists next_follow_up_type text,
  add column if not exists next_follow_up_note text;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'deals_product_id_fkey') then
    alter table public.deals add constraint deals_product_id_fkey foreign key (product_id) references public.products(id) on update cascade on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'deals_lead_source_id_fkey') then
    alter table public.deals add constraint deals_lead_source_id_fkey foreign key (lead_source_id) references public.lead_sources(id) on update cascade on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'deals_primary_contact_id_fkey') then
    alter table public.deals add constraint deals_primary_contact_id_fkey foreign key (primary_contact_id) references public.contacts(id) on update cascade on delete restrict;
  end if;
end $$;

create index if not exists deals_product_id_idx on public.deals(product_id);
create index if not exists deals_lead_source_id_idx on public.deals(lead_source_id);
create index if not exists deals_primary_contact_id_idx on public.deals(primary_contact_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path to 'public'
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.log_cplay_deal_changes()
returns trigger
language plpgsql
set search_path to 'public'
as $$
begin
  if old.stage is distinct from new.stage then
    insert into public.deal_notes (deal_id, type, text, date)
    values (new.id, 'system', 'Etapa alterada de "' || coalesce(old.stage, 'não informada') || '" para "' || coalesce(new.stage, 'não informada') || '".', now());
  end if;

  if old.sales_id is distinct from new.sales_id then
    insert into public.deal_notes (deal_id, type, text, date)
    values (new.id, 'system', 'Responsável comercial alterado.', now());
  end if;

  if old.amount is distinct from new.amount then
    insert into public.deal_notes (deal_id, type, text, date)
    values (new.id, 'system', 'Valor da oportunidade alterado de ' || coalesce(old.amount::text, 'não informado') || ' para ' || coalesce(new.amount::text, 'não informado') || '.', now());
  end if;

  if old.next_follow_up_at is distinct from new.next_follow_up_at
     or old.next_follow_up_type is distinct from new.next_follow_up_type
     or old.next_follow_up_note is distinct from new.next_follow_up_note then
    if old.next_follow_up_at is not null
       or old.next_follow_up_type is not null
       or old.next_follow_up_note is not null then
      insert into public.deal_notes (deal_id, type, text, date)
      values (
        new.id,
        'follow_up',
        'Follow-up anterior: ' || coalesce(old.next_follow_up_at::text, 'sem data') ||
        case when old.next_follow_up_type is not null then ' | ' || old.next_follow_up_type else '' end ||
        case when old.next_follow_up_note is not null and old.next_follow_up_note <> '' then ' | ' || old.next_follow_up_note else '' end,
        now()
      );
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists products_set_updated_at on public.products;
create trigger products_set_updated_at before update on public.products
for each row execute function public.set_updated_at();

drop trigger if exists lead_sources_set_updated_at on public.lead_sources;
create trigger lead_sources_set_updated_at before update on public.lead_sources
for each row execute function public.set_updated_at();

drop trigger if exists cplay_deal_history on public.deals;
create trigger cplay_deal_history after update on public.deals
for each row execute function public.log_cplay_deal_changes();

alter table public.products enable row level security;
alter table public.lead_sources enable row level security;

drop policy if exists "Products read for authenticated users" on public.products;
create policy "Products read for authenticated users" on public.products for select to authenticated using (true);
drop policy if exists "Products insert for authenticated users" on public.products;
create policy "Products insert for authenticated users" on public.products for insert to authenticated with check (true);
drop policy if exists "Products update for authenticated users" on public.products;
create policy "Products update for authenticated users" on public.products for update to authenticated using (true) with check (true);
drop policy if exists "Products delete for authenticated users" on public.products;
create policy "Products delete for authenticated users" on public.products for delete to authenticated using (true);

drop policy if exists "Lead sources read for authenticated users" on public.lead_sources;
create policy "Lead sources read for authenticated users" on public.lead_sources for select to authenticated using (true);
drop policy if exists "Lead sources insert for authenticated users" on public.lead_sources;
create policy "Lead sources insert for authenticated users" on public.lead_sources for insert to authenticated with check (true);
drop policy if exists "Lead sources update for authenticated users" on public.lead_sources;
create policy "Lead sources update for authenticated users" on public.lead_sources for update to authenticated using (true) with check (true);
drop policy if exists "Lead sources delete for authenticated users" on public.lead_sources;
create policy "Lead sources delete for authenticated users" on public.lead_sources for delete to authenticated using (true);

grant all on function public.set_updated_at() to anon, authenticated, service_role;
grant all on function public.log_cplay_deal_changes() to anon, authenticated, service_role;
grant all on table public.products to anon, authenticated, service_role;
grant all on table public.lead_sources to anon, authenticated, service_role;
grant all on sequence public.products_id_seq to anon, authenticated, service_role;
grant all on sequence public.lead_sources_id_seq to anon, authenticated, service_role;
